spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: "jdbc:postgresql://0.0.0.0:5432/pollapi"
    username: "pollapi"
    password: "pollapi"
    driver-class-name: org.postgresql.Driver
  jpa:
    database: "default"
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type: trace
        show_sql: true
        format_sql: true
        ddl-auto: create-drop
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

  resources:
    chain:
      enabled: true